### ISSUE TITLE
npm i problem

### ISSUE THREAD

**Issue by splincode** [Robinyo/angular-wijmo-flexsheet#2]
```
$ npm i
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../../rob/WebStorm-2017/workspace/products/wijmo-5-enterprise/NpmImages/wijmo-amd-min" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/splincode/.npm/_logs/2017-11-22T20_39_04_473Z-debug.log

```

**Comment by Robinyo** [comment]
See: https://robferguson.org/blog/2017/08/28/angular-cli-angular-4-and-wijmo-flexsheet/

The wijmo FlexSheet download includes npm images of the Wijmo external modules in the /NpmImages folder. We can add wijmo to our project using npm:

    npm install --save ~/downloads/wijmo-5-enterprise/NpmImages/wijmo-amd-min"

Update `package.json`:

    "wijmo": "file:///home/rob/WebStorm-2017/workspace/products/wijmo-5-enterprise/NpmImages/wijmo-amd-min",

**Comment by splincode** [comment]
add an additional description in the installation for installation

**Comment by Robinyo** [comment]
Updated the README.md file:

->

To install the project's dependencies:

    cd angular-wijmo-flexsheet
    npm install

The wijmo FlexSheet [download](https://www.grapecity.com/en/wijmo-flexsheet) includes npm images of the Wijmo external 
modules in the `/NpmImages` folder. You can add wijmo to your project using npm:

    npm install --save ~/downloads/wijmo-5-enterprise/NpmImages/wijmo-amd-min

->
